### ISSUE TITLE
not working 

### ISSUE THREAD

**Issue by Abu-Sagidolla** [WheteThunger/TargetableDrones#3]
hi , tried to test your script , but it not working 
.

**Comment by WheteThunger** [comment]
Which feature did you test? Turret targeting, sam site targeting, or NPC targeting? Do you have any other plugins that affect turrets, sam sites, or NPCs?

**Comment by Abu-Sagidolla** [comment]
i have additional plugin "TOOL CUPBOARD TURRETS" and it conflictes with it 
i tried to test it on drones, placed sam and turrets and nearby at nearby started to controll rc drone. they werent shoot

**Comment by WheteThunger** [comment]
The problem may be how you are testing. It looks like this isn't currently documented, but sam sites places by you, and auto turrets placed by you, will not target drones that you are controlling.

**Comment by Abu-Sagidolla** [comment]
![image](https://github.com/WheteThunger/TargetableDrones/assets/56884868/89dca201-f70a-458b-b172-04c62a87d9fa)

**Comment by Abu-Sagidolla** [comment]
i placed by command static sam , still not working

**Comment by WheteThunger** [comment]
Can you confirm you have not granted the untargetable permission to yourself (since that permission would prevent your drones from being targeted)? Can you also share your config?

**Comment by Abu-Sagidolla** [comment]
yes didnt typed anythin

**Comment by Abu-Sagidolla** [comment]
![image](https://github.com/WheteThunger/TargetableDrones/assets/56884868/72ef523c-b96c-4c20-816d-424a795a56bc)

**Comment by WheteThunger** [comment]
Ok, from what I can see in the plugin code, that is supposed to be working. I will test when I get home to see if I can reproduce the issue, in case there has been a regression.

I looked at the Tool Cupboard Turrets plugin, but I don't think that will affect Sam Sites.

**Comment by Abu-Sagidolla** [comment]
thank u for ur reply

**Comment by WheteThunger** [comment]
I just tested and found the plugin to be working as expected. Here is what I did.

1. `o.unload all`
2. `o.load TargetableDrones`
3. `spawn sam_static`
4. `give drone`
5. Placed the drone, gave it an ID
6. Entered the ID into the computer station, selected it
7. Flew the drone near the Sam Site, and saw that rockets were fired at the drone

I suggest you follow the same steps, then load the rest of your plugins and test again. This will confirm whether the issue is related to your other plugins.

I took a closer look at Tool Cupboard Turrets. It does have the ability to block Sam Site targeting, but only for helicopters, so it shouldn't be the issue.

**Comment by Abu-Sagidolla** [comment]
same issue

**Comment by WheteThunger** [comment]
Then I suppose the only thing I can do is make a debug version of the plugin which prints information about what is going on, and you can install that version so we can see what the print statements say. Would you be open to this? I can have it ready in the next day or two.

**Comment by WheteThunger** [comment]
Hi, are you still experiencing this issue? If so, would you like to move forward with the debug version?

**Comment by Abu-Sagidolla** [comment]
hi , yes 
how to move to debug version

**Comment by WheteThunger** [comment]
Install this version of the plugin.

https://raw.githubusercontent.com/WheteThunger/TargetableDrones/debug/TargetableDrones.cs

It will print many debug messages. Some examples:

```
[Targetable Drones] Attached Sam Site targeting component to drone

[Targetable Drones] OnSamSiteTargetScan [376469] : 1 targetable drones on the map
[Targetable Drones] OnSamSiteTargetScan [376469] : 1 potential drone target(s) in range

[Targetable Drones] OnSamSiteTarget [376469] : Allowing targeting of drone because Sam Site is static or unowned.
[Targetable Drones] OnSamSiteTarget [376469] : Allowing targeting of drone because it has no owner and no controller.
[Targetable Drones] OnSamSiteTarget [376469] : Disallowing targeting of drone because of same owner/team/friends/clan/allies as Sam Site owner.
[Targetable Drones] OnSamSiteTarget [376469] : Allowing targeting of drone because no conditions prevented it.

[Targetable Drones] IsTargetable [687072] : Drone is not targetable because it is grounded
[Targetable Drones] IsTargetable [687072] : Drone is targetable because Sam Site is static.
[Targetable Drones] IsTargetable [687072] : Drone is not targetable because controller or owner is exempt.
[Targetable Drones] IsTargetable [687072] : Drone is targetable because it's not inside a safe zones.
[Targetable Drones] IsTargetable [687072] : Drone is not targetable because it's inside a safe zone.
```

The "OnSamSiteTargetScan" messages will happen quite often, as the Sam Sites scan often. If those particular messages get too spammy, you can delete the lines of code that prints them.

Once you try flying a drone near a Sam Site again, take note of which info is printed, and share that here.

**Comment by Abu-Sagidolla** [comment]
![Uploading image.png…]()

**Comment by Abu-Sagidolla** [comment]
![image](https://github.com/WheteThunger/TargetableDrones/assets/56884868/95d62756-d7f3-4e0e-a49a-4c6c6bcb6521)

**Comment by Abu-Sagidolla** [comment]
it works

**Comment by Abu-Sagidolla** [comment]
sorry

**Comment by Abu-Sagidolla** [comment]
its my problem

**Comment by WheteThunger** [comment]
Ok looks like you must have granted yourself the untargetable permission.
